version: '3.7'

services:

  app:
    build:
      context: ./
      dockerfile: Docker/app.dockerfile
    
  web:
    build:
      context: ./
      dockerfile: Docker/web.dockerfile
    ports:
      - 127.0.0.1:8880:80
  
  database:
    image: mariadb:latest
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 127.0.0.1:3366:3306
    environment:
      - "MYSQL_DATABASE=mariadb"
      - "MYSQL_USER=mariadb"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"

  # redis
  #cache:
  #  image: redis:3.0-alpine

volumes:
  dbdata: